name: Cleanup PR Log Groups

on:
  pull_request:
    types: [closed]
    branches:
      - development

env:
  AWS_REGION : "us-west-2"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  cleanup-logs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ secrets.ACTIONS_WEBHOOK_ROLE_ARN }}"
          role-session-name: "GitHub-PR-${{ github.event.pull_request.number }}-Cleanup"
          aws-region: ${{ env.AWS_REGION }}

      - name: Cleanup PR log group
        run: |
          awscurl --service execute-api \
            --region us-east-1 \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"logGroupSuffix": "-TypeScript-PR-${{ github.event.pull_request.number }}"}' \
            "${{ secrets.LOG_GROUP_CLEANUP_WEBHOOK }}"
